---

- name: sudo | packages
  tags:
  - package
  package:
    name: sudo

- name: sudo | enable passwordless sudo
  tags:
  - config
  lineinfile:
    dest: /etc/sudoers
    regexp: '^%sudo'
    line: "%sudo   ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: sudo | preserve ssh agent
  tags:
  - config
  lineinfile:
    dest: /etc/sudoers
    regexp: 'env_keep'
    line: 'Defaults     env_keep+="SSH_AUTH_SOCK"'
    validate: "/usr/sbin/visudo -cf %s"

- name: sudo | add user to group
  tags:
  - user
  user:
    name: "{{ sudo_user }}"
    groups: "sudo"
    append: yes

- name: sudo | lock root account
  user:
    name: root
    password: "!"

