---

- name: sudo | packages
  tags:
  - package
  package:
    name: sudo

- name: sudo | group
  tags:
  - group
  group:
    name: "{{ item }}"
  loop:
    - sudo
    - adm

- name: sudo | enable passwordless sudo
  tags:
  - config
  lineinfile:
    dest: /etc/sudoers
    regexp: '^%sudo'
    line: "%sudo   ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: sudo | preserve ssh agent
  tags:
  - config
  lineinfile:
    dest: /etc/sudoers
    regexp: 'env_keep'
    line: 'Defaults     env_keep+="SSH_AUTH_SOCK"'
    validate: "/usr/sbin/visudo -cf %s"

- name: sudo | user
  tags:
  - user
  user:
    name: "{{ sudo_user }}"
    groups: "sudo,adm"
    shell: /bin/bash

- name: sudo | SSH keys
  tags:
  - ssh
  authorized_key:
    user: "{{ sudo_user }}"
    key: "{{ ssh_authorized_keys }}"
    exclusive: yes

- import_tasks: randpw.yml
