---

- name: sudo | check pre-generated password
  local_action:
    module: stat
    path: "{{ tinc_keydir }}"
  register: keydir

- name: sudo | generate random user password
  tags:
  - password
  set_fact:
    sudo_pw: "{{  }}"
  when: not pwfile.stat.exists
