---

- name: sudo | lock root account
  user:
    name: root
    password: "!"

- name: sudo | random user password
  tags:
    - password
  user:
    name: "{{ sudo_user }}"
    password: "{{ lookup('password', pw_store + '/' + inventory_hostname + ' encrypt=sha512_crypt') }}"
